// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njjstrqrwjygwyujdrzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qanN0cnFyd2p5Z3d5dWpkcnprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxOTU2NjcsImV4cCI6MjA2Mjc3MTY2N30.0fk1WVTBTxEaM4XodIyrJyhIzYPz_orsGK_c-WlJjJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);